SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FNI.FISH_TYPE = FI.FISH_TYPE
-- 현재 행(FI)이 속한 물고기 종류(FISH_TYPE)에서, 
-- 그 종류의 최대 길이와 같은 길이를 가진 행만 남겨라.
WHERE FI.LENGTH = (
    SELECT MAX(FI2.LENGTH)
    FROM FISH_INFO FI2
    WHERE FI2.FISH_TYPE = FI.FISH_TYPE
)
ORDER BY FI.ID;